### ISSUE TITLE
Label is not automatically removed

### ISSUE THREAD

**Issue by TomW-Skyline** [mschilde/auto-label-merge-conflicts#54]
The action automatically adds the "conflict" label when needed, but when we resolve the conflict it's not being removed.

This is how our yml file looks like:

```yml
on:
  # So that PRs touching the same files as the push are updated
  push:
   branches: 
      - '**'
      
  # So that the `dirtyLabel` is removed if conflicts are resolve
  # We recommend `pull_request_target` so that github secrets are available.
  # In `pull_request` we wouldn't be able to change labels of fork PRs
  pull_request_target:
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if prs are dirty
        uses: mschilde/auto-label-merge-conflicts@v2.0
        with:
          CONFLICT_LABEL_NAME: "conflict"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```
